### ISSUE TITLE
Adding meow-mode (noob question)

### ISSUE THREAD

**Issue by imadnyc** [terlar/emacs-config#355]
Hey, your repo is really cool and appealing to me as a nix user, but I'm confused on how you setup your `init.org`.

I'm trying to add meow-mode, and am trying to add https://github.com/Imymirror/imy-emacs.d/blob/f7e488fd51e76a51d2a0b71f1d4255b018b95bd4/.vanilla-emacs.d/lisp/init-meow.el#L199 into a section in the `init.org`. The issue is that it can't seem to find `meow-setup` because the linter is being really strict (or so I'm told by the #emacs channel on IRC). Do you have any pointers to how I should configure this? Other emacs configs have been really arcane to sift through so I appreciate your literate config.

**Comment by terlar** [comment]
Hello, thank you for the appreciation. Yes, it is strict, it is just the way I prefer, I rather catch potential issues at "compile-time".

If you prefer not to be so strict, you can disable that flag `byte-compile-error-on-warn` here:
https://github.com/terlar/emacs-config/blob/main/default.nix#L51

With `use-package` you can let the compiler know that this block will have that function defined by adding a keyword:
```
:commands meow-setup
```

There is also `:functions` and in certain cases, I was using `autoload` in a `:preface`. So if you don't want to bother with that just remove that flag.

**Comment by imadnyc** [comment]
Thanks! I'm sure that there's a way to make my config work with strict mode, but for now this lets me actually use it. Appreciate the help so much!
